### PR TITLE
Add Bitcoin Core v25.1

### PR DESCRIPTION
**Pull request by andrewtoth**

### CODE REVIEW

**Comment by RCasatta** [comment]
ACK e5ec8f41ec2d15be4234fa87b9eab73af073989e

Thanks

Usually, only the greater minor version is kept (so we will remove 25.0) to keep the number of features manageable...
But we can remove later on

**Comment by RCasatta** [comment]
...CI error is unrelated to this MR and will be fixed separately

**Comment by andrewtoth** [comment]
> But we can remove later on

Err sorry, but removing features is a breaking change. Should bump major version for each feature removal I think?

**Comment by RCasatta** [comment]
Yeah, It should be major but in the past I did a minor version changes for this kind of stuff since I am stuck with the `0.*` version

I should probably do a minor to major version migration like Bitcoin core

**Pull request merged**
