### PR TITLE
feat: Add specific error type for -rpcuser and -rpcpassword usage

### LINKED ISSUE #68: Cannot use `-rpcuser` and `-rpcpassword` as arguments, does not return Err and enters infinite loop
**Describe the bug**  
Cannot use `-rpcuser=<user>` and `-rpcpassword=<password>` args with `bitcoind`, although it's indicated to be deprecated when running `bitcoind` from the binaries I think it's useful and would be great to maintain compatibility.

The `-rpcuser` and `-rpcpassword` does not create a `.cookie` file, therefore it produces an error when trying to read from the file and get auth parameters.

It enters in an infinite loop because it cannot create and connect a RPC client in step: [`let client_result = Client::new(&rpc_url, Auth::CookieFile(cookie_file.clone()));`](https://github.com/RCasatta/bitcoind/blob/master/src/lib.rs#L301) when calling `auth.get_user_pass` it returns an io error because the file does not exists, but the error is not treated and it skip to another pass in the loop considering it's just because the process is not up yet.

It would be better to not consider the .cookie file when receiving `-rpcuser` and `-rpcpassword` arguments or raise an error recommending to use `-rpcauth`, which works because it uses user and password and creates a .cookie file, and I'm using as a workaround. 

**To Reproduce** 
You can simply try to start a process passing the  `-rpcauth` and `-rpcpassword` as arguments in conf, it won't event start the process.
I've created two tests here: https://github.com/oleonardolima/bitcoind/commit/b522d5ec1c42584b81c3b6595e36b9df0b2517f6
- one for reproducing the error for `-rpcuser` and `-rpcpassword`, recommended to run with debug logs: https://github.com/RCasatta/bitcoind/commit/b522d5ec1c42584b81c3b6595e36b9df0b2517f6#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R621-R643
- one to show that for `-rpcauth` works successfully: https://github.com/RCasatta/bitcoind/commit/b522d5ec1c42584b81c3b6595e36b9df0b2517f6#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R645-R668

**Expected behavior**  
I expect that it would work successfully or return an error indicating that it's indicated to use -rpcauth instead.

**Build environment**  
 - bitcoind tag/commit: `v0.13.0` | `bd952c186ffa30e328a7b12c350569856b43c7c1` 
 - OS+version: `macOS 12.4`  
 - Rust/Cargo version: `rustc 1.60.0 (7737e0b5c 2022-04-04)` | `cargo 1.60.0 (d1fd9fe2c 2022-03-01)`
 - Rust/Cargo target: `aarch64-apple-darwin`

### PR DESCRIPTION
**Pull request by oleonardolima**
## Description
As discussed in #68 trying to use the `-rpcuser` and `-rpcpassword` leads to an infinite loop, because this authentication method does not work alongside cookie authentication leading to an empty file, and the BitcoinD keeps retrying indefinitely.

This PR adds:
- a new Error variant for this `RpcUserAndPasswordUse`
- a new function to validate the args specified
- two new tests, one for `-rpcuser` and `-rpcpassword` usage, which asserts a failure, and another one for the usage of `-rpcauth` which works fine alongside cookie authentication. 

Fixes #68

### CODE REVIEW

**Comment by RCasatta** [comment]
Concept ACK.

I would prefer not to add the "regex" crate if not strictly necessary, in this case, I think `fn starts_with` could do the job without an additional dependency?

Without `regex` this PR is an improvement and already mergeable to me.

A further improvement is to make `args` field a new type `Args` struct with a couple of functions to add an arg (at this point check arg validity) and to returns the args. This struct should consider also https://github.com/RCasatta/bitcoind/issues/39

**Comment by oleonardolima** [comment]
> Concept ACK.
> 
> I would prefer not to add the "regex" crate if not strictly necessary, in this case, I think `fn starts_with` could do the job without an additional dependency?
> 
> Without `regex` this PR is an improvement and already mergeable to me.
> 
> A further improvement is to make `args` field a new type `Args` struct with a couple of functions to add an arg (at this point check arg validity) and to returns the args. This struct should consider also #39

@RCasatta Thanks for the review and the suggestion

Yep, it does not really need the regex to do it, I updated it to have an invalid argument list and check from that list using the `starts_with` instead.

**Comment by RCasatta** [comment]
utACK 54e444aef5b0d38028deea374da95744e72db066

Ideally when commits in the same PR touch the same lines touched by other commits in the same PR is better to squash, next time :)

**Comment by oleonardolima** [comment]
> utACK [54e444a](https://github.com/RCasatta/bitcoind/commit/54e444aef5b0d38028deea374da95744e72db066)
> 
> Ideally when commits in the same PR touch the same lines touched by other commits in the same PR is better to squash, next time :)

Thanks, I forgot to squash it, sorry 😁

**Pull request merged**
